# Generated by Django 6.0.1 on 2026-03-26 21:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovaite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclinktoken',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='magiclinktoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='magiclinktoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
